---
- hosts: localhost
  gather_facts: false
  collections:
    - redhat.jcliff
  roles:
    - jcliff

  tasks:
    - jcliff:
        wfly_home: "{{ jboss_home }}"
        rule_file: /dev/null
        subsystems:
          - system_props:
              - name: jcliff.enabled
                value: 'enabled'
